spring:
    application:
        name: registry

server:
    port: 8761

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
